### ISSUE TITLE
Hide Python internal tracing

### ISSUE THREAD

**Issue by moshix** [SYSPROG-JLS/S370BALAsm#2]
Hello

Would it be possible to hide the Python internal trace stack and only show the assembly errors (like syntax etc.)?

This way, I could just catch the errors in a bash script and integrate with my IDE. 

Many thanks

M

**Comment by SYSPROG-JLS** [comment]
Hi Moshix,
As you have discovered, there is precious little catching of assembly errors and the reporting of them like a normal assembler would do. I will endeavor to compile a list of common errors and put code in to catch them.

**Comment by moshix** [comment]
thank you Jim. I will certainly make a video about this assembler. Very easy to use and set up for 99% of users out there!

thanks

M
