### ISSUE TITLE
Example of file reading and file writing

### ISSUE THREAD

**Issue by moshix** [SYSPROG-JLS/S370BALAsm#3]
Hello JIm

Do you have an example of a simple program opening, reading, then writing and closing from a PC file?

I saw the SVCs you provide and the registers needed, but couldn't quite get it to work. 

Many thanks!

M

**Comment by SYSPROG-JLS** [comment]
Hi Moshix,

Under SYSPROG-JLS/S370BALEmulator I have added S370GETSample.mlc & S370PUTSample.mlc. These demonstrate opening, reading, then writing and closing from a PC file.

Jim

**Comment by moshix** [comment]
got it! thank you so much!

Moshix
