### ISSUE TITLE
DOS

### ISSUE THREAD

**Issue by HempCIO** [SYSPROG-JLS/S370BALAsm#5]
Any plans on updating for DOS/VSE? Not everyone runs MVS.

**Comment by SYSPROG-JLS** [comment]
Hello HempCIO,

Thanks for your feedback
Give me a list of changes you would like to see incorporated.
I assume that you might want to see support for DTFs - what else would you like to see?

**Comment by HempCIO** [comment]
well besides the DTF's there are OPENR, PUTR, GETR macros. there is a manual for DOS.VSE assembly lang programming
here is a link you might want to reference
https://www.ibm.com/docs/he/zvm/7.2?topic=macros-vse-assembler-language-supported

**Comment by SYSPROG-JLS** [comment]
Thanks for your input HempCIO.
Yes, I am very well acquainted with that manual.
I just wanted to see what changes you thought were important.
I'll see when I can get to work on this.
Also if you are so inclined please feel free to contribute yourself.
That's what Open Source is all about.

**Comment by SYSPROG-JLS** [comment]
At this time I do not wish to pursue this change.
Even for users who only know DOS(VSE), I believe they will find the provided IO macros easy to learn and use.
